### PR TITLE
Add dryRun flag

### PR DESCRIPTION
**Pull request by jhaber**
If set, the DryRunFileUploader is used which just generates the JSON file and doesn't actually upload anything

### CODE REVIEW

**Comment by jbau** [comment]
Hey @jhaber thanks for the improved PR.  Yes, I think this supports my use case and is better modularized than my version, so I'm all for it 👍.  `dryRun` as the flag name sounds good to me also.

**Comment by jhaber** [comment]
Awesome, I'll cut a release in the morning

**Comment by jhaber** [comment]
@jbau I just released version 0.13 which includes this feature, it should show up in Maven central soon

**Comment by jbau** [comment]
great! thanks

**Comment by a-zen** [comment]
Any news on how this 0.13 is on maven? I really like to use the dryRun feature.

**Comment by jhaber** [comment]
That's odd, I'm not sure what happened. I just released 0.14 which should show up in central soon (if it's not there by tomorrow I'll see if there's some underlying issue with our release process)

**Comment by a-zen** [comment]
Great it's now in [maven](http://search.maven.org/#artifactdetails%7Ccom.hubspot.maven.plugins%7Cslimfast-plugin%7C0.14%7Cmaven-plugin).
I will try it out. 👍

**Pull request merged**
